//! Forgeconf - ergonomic configuration loading for Rust structs.
//!
//! The `#[forgeconf]` attribute builds a dedicated loader that merges
//! configuration files, CLI flags, and environment variables in a predictable
//! order while checking type safety at compile time.
//!
//! # Example
//! ```
//! use forgeconf::{forgeconf, ConfigError};
//!
//! #[forgeconf(config(path = "tests/fixtures/basic.toml"))]
//! struct AppConfig {
//!     #[field(default = 8080)]
//!     port: u16,
//!     #[field(env = "APP_DATABASE_URL")]
//!     database_url: String,
//! }
//!
//! fn main() -> Result<(), ConfigError> {
//!     unsafe { std::env::set_var("APP_DATABASE_URL", "postgres://override"); };
//!     let cfg = AppConfig::loader()
//!         .load()?;
//!     println!("listening on {}", cfg.port);
//!     println!("db url: {}", cfg.database_url);
//!     Ok(())
//! }
//! ```

#[cfg(feature = "clap")]
pub use clap;

/// Prefix-aware clap integration trait. Generated by `#[forgeconf]` for every
/// annotated struct when the `clap` feature is enabled.
///
/// - `augment_clap_with_prefix` — adds this struct's fields to a `Command`,
///   prefixing arg IDs and long names when `prefix` is `Some`.
/// - `extract_clap_with_prefix` — reads matched values from `ArgMatches` and
///   inserts them into `out` using dotted keys (`watcher.watch_path`), which
///   `CliArgsSource::load` then expands into a nested `ConfigNode` tree.
///
/// You normally don't implement this yourself; `#[forgeconf]` does it.
#[cfg(feature = "clap")]
pub trait ForgeconfClap {
    fn augment_clap_with_prefix(cmd: clap::Command, prefix: Option<&str>) -> clap::Command;

    fn extract_clap_with_prefix(
        matches: &clap::ArgMatches,
        prefix: Option<&str>,
        out: &mut std::collections::BTreeMap<String, String>,
    );
}
#[cfg(all(feature = "parse", feature = "json"))]
pub use forgeconf_core::parse_json;
#[cfg(feature = "parse")]
pub use forgeconf_core::parse_str;
#[cfg(all(feature = "parse", feature = "toml"))]
pub use forgeconf_core::parse_toml;
#[cfg(all(feature = "parse", feature = "yaml"))]
pub use forgeconf_core::parse_yaml;
#[cfg(feature = "validators")]
pub use forgeconf_core::validators;
#[cfg(feature = "cli")]
pub use forgeconf_core::{CliArgsSource, CliArguments};
pub use forgeconf_core::{
    ConfigBuilder,
    ConfigError,
    ConfigFile,
    ConfigNode,
    ConfigSource,
    FileFormat,
    FromNode,
    load_from_path,
    merge_nodes,
};
pub use forgeconf_macros::forgeconf;
